### ISSUE TITLE
05/17 회의록

### ISSUE THREAD

**Issue by SongDerrick** [SongDerrick/Mudo_White_List#6]

**Comment by siddharth0a** [comment]
유료강의 https://www.udemy.com/course/the-web-developer-bootcamp-2021-korea/
생활코딩 유튜브
구글링
6월 종강 후부터 시작

**Comment by yangju99** [comment]
# 5/22 일요일 회식 5시 30분!

1. 공직선거법 
- 위반사례: 선거 여론 조사 표본에 대해 정보를 주지 않거나 조작했을 때 ( 공약 비교는 문제되지 않음) 
- 공직선거법 허위 사실 공표죄: 공약 정보 업로드 전에 후보자에게 직접 검증받기 후보자 컨텍으로 공약집 얻기 

2. 코딩 공부(유료 강의, 무료강의?) 
-맹경덕: udemy korea (링크 올릴 예정) 종강 이후 2주간  7월 3일 출국? 
-권수민: 생활코딩 유튜브 강의 (자바스크립트) 일단 5월까지, 종강 이후 유료 강의로 프론트엔드 위주로 공부   
-황인선: 이미 무제한으로 결제한 사이트 있음.  인프런 6월 19일 출국?
-양주영: 유료강의 무조건 들을 예정 (udemy korea: The Web Developer 부드캠프 2022)  종강 이후 2주간  
-송도윤: 종강 이후 2주동안 udemy 복습( 서버 다 만들어 오겠다고 함) 

3.첫화면 디자인 및 내용?

#내년 4월 재보궐 선거에 배포 목표로 준비? 
#notion으로 한 번 예시 만들어보기(6월 1일 광주교육감 선거)
- 후보 1명씩 전담하여 핵심 공약 3개 추려서 조사해오기, why how 포함  
 
- 후보자 2명 먼저 고르고 관심 분야 카테고리 선택-> 관심 분야 공약 비교해줌
서브 페이지 만들기 

-공약을 쉽게 전달(공약에 대한 사전배경 및 why, how 까지  포함?, 구체적인 실현 방안) 

-주관식으로 관련 단어 검색-> 가장 관련도 높은 후보 보여줌. 

-category:  관심 분야 공약  분류 ex) 교육, 경제, 복지, 국방, 의료, 공중보건  



해야 할것: notion 사이트에 후보 1명씩 전담하여 핵심 공약 3개 추려서 조사해오기, why how 포함
깃허브에 공부할 강의 링크 올리기

**Comment by inthree3** [comment]
https://www.inflearn.com/course/%EB%A7%8C%EB%93%A4%EB%A9%B4%EC%84%9C-%EB%B0%B0%EC%9A%B0%EB%8A%94-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EA%B8%B0%EC%B4%88
![image](https://user-images.githubusercontent.com/42310616/168813939-fde63271-eaf7-47de-85bb-e38c3dcb6e4c.png)
