### ISSUE TITLE
05/23 회의록

### ISSUE THREAD

**Issue by SongDerrick** [SongDerrick/Mudo_White_List#7]

**Comment by inthree3** [comment]
### 지난 steps
- 각 담당 후보의 공약들 Notion에 정리 [ ]
  - 황인선 [ ]
  - 권수민 [ ]
  - 맹경덕 [ ]
  - 송도윤 [ ]
  - 주영 [ ]

### 회의 Agenda 
- Beta로 제작하기로 한 Notion page가 해결하고자 하는 Problem은 무엇인가? (각자 조사하면서 느낀 점 공유, 투표 결정 시에 겪는 어려움 등) [ ]
- '화이트 리스트'의 vision은 무엇인가? (느낀 점을 기반으로 우리가 **사람**들에게 줄 수 있는 가치 제안, 문제 해결을 통해 끼치고 싶은 영향력) [ ]
- Notion 페이지 역할 분배 [ ]

### Next steps
- Notion 페이지 제작 (05-28까지 배포?) [ ]
- 홍보글 작성 [ ]

**Comment by inthree3** [comment]
- [ ] 체크박스
- [ ]

**Comment by inthree3** [comment]
### 회의 Agenda
 Beta로 제작하기로 한 Notion page가 해결하고자 하는 Problem은 무엇인가? (각자 조사하면서 느낀 점 공유, 투표 결정 시에 겪는 어려움 등)
  - 이미 선거관리위원회에서 공약을 잘 보여주고 있어서 차별점을 만들어주는 것이 필요(도윤)
  - 비교하는 부분을 강조하자(주영)
  - 좋은 공약이라고 생각하는 것에 좋아요, 투표 기능 추가(경덕)
  - 사이트에 들어오게 할 방법이 있어야할 것 같다(경덕) 공약을 보고 싶은 사람이 있을 거라는 생각(인선)
  - 정보를 잘 정리하면 공약을 보러 올 것이다(가설)
  - 귀찮아서, 관심이 없어서, 있는 줄 몰라서 -> 교육감 직선제가 생기게 된 계기를 보여주면 해결되지 않을까(인선)
  - 선거의 필요성 등 설명해주자(도윤)
  - 정리를 하기가 애매했다(수민)
  - 키워드를 뽑아서 정리해보자(도윤) - 할 수 있을 것 같다(인선)
  - 뭘 하겠다는지 애매한 것은 정리할 때 제외함(주영)
  - 묶일만한 공약을 묶어내자(도윤)
  - 카테고리화해서 선호에 대한 카테고리를 주자(경덕)
  - 교육감 공약에 카테고리를 정리하기가 어려울 것 같다(인선)
  - 교육감 MBTI처럼 만들자(도윤)
  - 정치에 관한 지식이 없는 사람들이 전문성이 의심된다.(수민)
  - 키워드 데이터 기반으로 해보자(도윤)
  - 교수님의 자문을 받아서 해보자(인선)
  - 수학적 키워드 기반의 방식이 좋아보임. 주관적 생각이 개입되지 않는다. (주영)
  - 정량적 답변을 기반으로 가장 일치하는 사람으로 추천(도윤)
  - 우선순위로 해보자(인선), 가중치를 입혀서 사용해볼만한 문항, 다 섞어서 해보자(주영)
  - 알고리즘을 설계하는 과정에서 왜곡이 들어갈 수 있다(인선)
  - 문항을 반복적으로 답변할 수 있게 할 수 있지 않을까?(수민)
  - 문항의 순서를 바꾸는 것초자 주관식으로, 객관식, 정확도가 떨어지더라도, 사용자 수를 끌어올 수 있는 것으로(경덕)
  - 무상급식을 예시로 '보편적으로 전체에 주는 것이다.', 비교를 해준다.
  - 질문을 카테고리별로 구분한다. (ex. 국방: 대표 공약들을 나열하고, 이에 대한 선택을 할 수 있게 한다.)
  무상급식: 아침 간편식(100원), 전면 무상급식...)
 '화이트 리스트'의 vision은 무엇인가? (느낀 점을 기반으로 우리가 사람들에게 줄 수 있는 가치 제안, 문제 해결을 통해 끼치고 싶은 영향력)
 Notion 페이지 역할 분배
### 홍보방안
  - 페이스북, 인스타그램 페이지 등에 홍보하기
  -

**Comment by inthree3** [comment]
1. 급식
2. 미래 교육(AI), 소프트웨어 교육
3. 무상 교육
4. 학력 격차
5. 체험형 교육
6. 진로 진학
7. 수업의 질 향상
8. 인성교육
9. 지역 특색 교육
10. 보육

**Comment by SongDerrick** [comment]
https://www.notion.so/76a2ded016994b39aebbf2bbae9ac534
